export const DARK_MODE = "DARK_MODE";

export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";

export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";

export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_ERROR = "SIGN_OUT_ERROR";

export const ACTIVE_USER = "ACTIVE_USER";

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

export const CHANGE_DISPLAY_NAME_SUCCESS = "CHANGE_DISPLAYNAME_SUCCESS";
export const CHANGE_DISPLAY_NAME_ERROR = "CHANGE_DISPLAY_NAME_ERROR";

export const RESET_ERROR = "RESET_ERROR";

export const UPLOAD_POST_SUCCESS = "UPLOAD_POST_SUCCESS";
export const UPLOAD_POST_ERROR = "UPLOAD_POST_ERROR";

//
export const LOADING_MAIN = "LOADING_MAIN";
export const LOADING_SUB = "LOADING_SUB";
export const LOADING_PROGRESS = "LOADING_PROGRESS";
